# Generated by Django 4.2 on 2024-01-10 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_brand_post_capacity_post_color_post_horse_power_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='brand',
            field=models.CharField(max_length=128, null=True, verbose_name='BRANDS'),
        ),
        migrations.AlterField(
            model_name='post',
            name='color',
            field=models.CharField(max_length=128, null=True, verbose_name='COLORS'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='CREATED_DATE'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='DESCRIPTION'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts-images/', verbose_name='FOTO POST'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=128, null=True, verbose_name='TITLE'),
        ),
    ]
